<?php
$this->headTitle()->append('User');
?>
<div class="RightContent">
	<div class="ContentBox" >
		<h3 id="click_here">User List for Rest example</h3>
		<div class="ContentData" id="div1">
			<div class="clearb borderRight">
				<ul id="countrytabs" class="shadetabs"></ul> 
				<div class="tabingBox">
					<div id="country1" class="tabcontent" style="display:">
						<div class="TableContainer">
							<table width="100%" border="0" cellspacing="0" cellpadding="5">
								<thead>
									<tr>
										<th width="60%">Name</th>
										<th width="20%" class="Tcenter">Edit</th>
										<th width="20%" class="Tcenter">Delete</th>
									</tr>
								</thead>
								<tbody>
									<?php foreach($this->users as $user) : ?>
										<tr class="odd">
											<th width="60%"> <?php echo $this->escape($user['email']);?></th>
											<th width="20%" style="text-align:center;">
												<a href="<?php echo $this->url(array('controller'=>'restclient','action'=>'addedit', 'id'=>$user['id_user']));?>" title="Edit">
													<img src="/images/1286256291_edit.png"/>
												</a>
											</th>
											<th width="20%" style="text-align:center;">
												<a href="<?php echo $this->url(array('controller'=>'restclient','action'=>'delete', 'id'=>$user['id_user']));?>" title="Delete" class="deleteIcon">
													<img src="/images/1286256515_dialog-close.png"/>
												</a>
											</th>
										</tr>
									  <?php endforeach; ?>
								</tbody>
							</table>
						</div>
						<div class="ListingFooter"> 
							<a href="<?php echo $this->url(array('controller'=>'restclient','action'=>'addedit'));?>" class="addLink" title="Add User">Add User</a>
							</div>
						</div>
						<div class="clearb"></div>
					</div>
				</div>
				<div class="clearb"><div></div></div>
			</div>
		</div>
	</div>