<?php
$this->title = "Login";
$this->headTitle($this->title);
$form = $this->forgotPasswordForm;
?>
<form method="post">
	<table border=0>
		<?php if(isset($this->ssMessage)) { ?>
		<tr><td></td><td align="center"><?php echo $this->ssMessage; ?></td></tr>
		<?php } ?>

		<tr><td></td><td align="center"><?php echo $form->email->renderErrors()?></td></tr>
		<tr><td><?php echo $form->email->renderLabel()?></td><td><?php echo $form->email->renderViewHelper();?></td></tr>
		<tr><td></td><td><input type="submit" name="submit" value="Save"></td></tr>
	</table>
</form>