<td valign="top" width="3%" height="100%">
<div id="sideBar" >	
		<a href="#" id="sideBarTab"><img src="images/slide-button.png" alt="sideBar" title="sideBar" /></a>
        <div id="TMlogo"></div>
		<div id="sideBarContents" style="width:210px; ">
		<div id="sideBarContentsInner" >
            <dl>
                <dt class="WhiteButton"><a href="/user/list" >Common Example</a></dt>
            	<dt class="WhiteButton"><a href="/restclient" >Rest Example</a></dt>
            	<dt class="WhiteButton"><a href="/admin/category/list" >Category Example</a></dt>
            	<dt class="WhiteButton"><a href="/login/changepassword" >Change Password</a></dt>
             </dl>
		</div>
	</div>
		</div>
</td>		