<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('VirtueInfo PVT Ltd.');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/main.css'); ?>
		<?php //echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/tabcontent.css'); ?>
		<?php //echo $this->headScript()->appendFile($this->baseUrl().'/js/tabcontent.js'); ?>
	</head>
	<body class="loginBG">
		<div id="content">
			<?php echo $this->layout()->content; ?>				
		</div>
	</body>
</html>