<?php

/**
 * Model_Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zend-rest
 * @subpackage models
 * @author     Shashank Patel
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */

class Model_Users extends Model_Base_Users
{
	public  function saveUser($oFormValue = array())
	{
		if(!is_array($oFormValue) || empty($oFormValue)) return false;
		
		$ousers = new Model_Users();
		$ousers->email = $oFormValue['email'];
		$ousers->password = md5($oFormValue['password']);
		$ousers->first_name = ucfirst($oFormValue['first_name']);
		$ousers->last_name = ucfirst($oFormValue['last_name']);
		$ousers->city = ucfirst($oFormValue['city']);
		$ousers->save();
		return true;
	}
}
