<?php

/**
 * Model_Contacts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zend-rest
 * @subpackage models
 * @author     Shashank Patel
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Model_Contacts extends Model_Base_Contacts
{

}