Contacts:
  connection: doctrine
  tableName: contacts
  columns:
    id_contact:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    email:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
Users:
  connection: doctrine
  tableName: users
  columns:
    id_user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    email:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
    password:
      type: string(55)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
    first_name:
      type: string(55)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
    last_name:
      type: string(55)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
    city:
      type: string(55)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
Category:
  connection: doctrine
  tableName: category
  columns:
    id_category:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    category_name:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false